name: basic-kg-rag-env
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy < 2.0
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
