version: '3.8'

services:
  arangodb:
    image: arangodb:latest
    container_name: arangodb
    ports:
      - "${ARANGO_PORT:-8529}:8529"  # Default ArangoDB port
    environment:
      ARANGO_ROOT_PASSWORD: "${ARANGO_ROOT_PASSWORD}"
    volumes:
      - ./arangodb_data:/var/lib/arangodb3  # Persistent database storage
      - ./arangodb_apps:/var/lib/arangodb3-apps  # Optional: user-defined apps/scripts
    restart: "no"