version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    # expose 3306 inside, map to host port from .env
    ports:
      - "${PORT}:3306"
    # bind-mount local ./data for persistence
    volumes:
      - ./data:/var/lib/mysql
    # pass through any MySQL-specific env vars you have defined
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE:      "${MYSQL_DATABASE}"
      MYSQL_USER:          "${MYSQL_USER}"
      MYSQL_PASSWORD:      "${MYSQL_PASSWORD}"
    # no auto-restart on docker or host reboot
    restart: "no"